"""broker_port

Revision ID: 5baa5b5a1e80
Revises: 813d2c88b0c4
Create Date: 2024-12-27 12:15:23.709152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5baa5b5a1e80"
down_revision: Union[str, None] = "813d2c88b0c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "broker_details", sa.Column("broker_port", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("broker_details", "broker_port")
    # ### end Alembic commands ###
