"""update components table

Revision ID: 9db22a996d6e
Revises: 02955cc15633
Create Date: 2025-05-15 12:23:05.840026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9db22a996d6e"
down_revision: Union[str, None] = "02955cc15633"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("component", sa.Column("component_file", sa.String(), nullable=True))
    op.alter_column(
        "component",
        "input_path",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "component",
        "output_path",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_component",
        "input_path",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_component",
        "output_path",
        existing_type=sa.VARCHAR(),
        type_=sa.JSON(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pipeline_component",
        "output_path",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "pipeline_component",
        "input_path",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "component",
        "output_path",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "component",
        "input_path",
        existing_type=sa.JSON(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_column("component", "component_file")
    # ### end Alembic commands ###
