"""model_info_table

Revision ID: a3711cfde0df
Revises: 4fd38e9fefb3
Create Date: 2025-05-06 19:53:17.664428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3711cfde0df"
down_revision: Union[str, None] = "4fd38e9fefb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    dialect = inspector.dialect.name

    with op.batch_alter_table("model_info") as batch_op:
        if dialect == 'postgresql':
            batch_op.alter_column(
                "version",
                existing_type=sa.VARCHAR(),
                type_=sa.Integer(),
                existing_nullable=True,
                postgresql_using="version::integer",
            )
        else:
            batch_op.alter_column(
                "version",
                existing_type=sa.VARCHAR(),
                type_=sa.Integer(),
                existing_nullable=True,
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_info") as batch_op:
        batch_op.alter_column(
            "version",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
